<a href="https://colab.research.google.com/github/drishtibaranwal/Machine-learning-Projects-/blob/main/USA_Housing_using_Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing libraries 

import pandas as pd
import numpy as np

In [ ]:
# Importing Dataset

df= pd.read_csv("/content/Multiple Linear Regression Dataset.csv")
fn= pd.read_csv("/content/USA_Housing.csv")

In [ ]:

df.head()

Transportation  Stationary  Packaging  Revenue
0            1000        1200        150     1203
1            1200        1150        300     1603
2            1400        1000        450     2003
3            1000        1050        600     2403
4            1800        1000       1000     2803

In [ ]:
#training the model
from sklearn.linear_model import LinearRegression

#Creating a Linear Regression object 
model = LinearRegression()

In [ ]:
# X variables = Transportation	Stationary	Packaging
# Y variable = Revenue (output)

# fitting the dataset
model.fit(df[['Transportation', 'Stationary' , 'Packaging']] , df['Revenue'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
# Start making Predictions 

model.predict([[4200,1000,2500]])

array([6115.563678])

In [ ]:
model.predict([[10000, 9000, 50000  ]])

array([36567.22949069])

In [ ]:
# checkinh accuracy of model 

model.score(df[['Transportation', 'Stationary' , 'Packaging']] , df['Revenue'])

0.9090591387521104

In [ ]:
# Checking the coefficients 
model.coef_

array([ 0.3047125 , -3.60438683,  1.21093532])

In [ ]:
model.intercept_

5412.819686364769